version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coffee_shop
    ports:
      - '3306:3306'
    networks:
      - coffee-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=coffee_shop
    networks:
      - coffee-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '80:80'
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge
