version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: coffee_shop
    ports:
      - '3306:3306'
    networks:
      - coffee-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=password
      - DB_NAME=coffee_shop
    networks:
      - coffee-network
    # อาจจะต้องการเพิ่มการรีไทร์ หรือการเช็คการเชื่อมต่อก่อนเริ่มทำงาน
    command: ["sh", "-c", "until nc -z -v -w30 db 3306; do echo 'Waiting for MySQL...'; sleep 1; done; node server.js"]

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    networks:
      - coffee-network

networks:
  coffee-network:
    driver: bridge
